export default function getProductImages() {
  return [
    {
      imgSrc: "../images/shopping/sofa.jpg",
      price: 1342.44,
      alt: "sofa",
      name: "sofa",
      category: "LivingRoom",
      color: "Gray",
      id: "CaLiCGS",
    },
    {
      imgSrc: "../images/shopping/WideLoungeChair.jpg",
      price: 999,
      alt: "Wide Lounge Chair",
      name: "Wide Chair",
      category: "BedRoom",
      color: "Brown",
      id: "CaBeCBWi",
    },
    {
      imgSrc: "../images/shopping/LeatherSwivelLoungeChair.jpg",
      price: 1599.99,
      alt: "Leather Swivel Lounge Chair",
      name: "Leather Chair",
      category: "BedRoom",
      color: "White",
      id: "CaBeCwNle",
    },
    {
      imgSrc: "../images/shopping/Wide Tufted.jpg",
      price: 569.99,
      alt: "Wide Tufted",
      name: "Wide Tufted",
      category: "LivingRoom",
      color: "Gray",
      id: "CliCGrNwi",
    },
    {
      imgSrc: "../images/shopping/Velvet Square Arm Loveseat.jpg",
      price: 689.99,
      alt: "Velvet Square Arm Loveseat",
      name: "Velvet Loveseat",
      category: "LivingRoom",
      color: "White",
      id: "CliCwNve",
    },
    {
      imgSrc: "../images/shopping/Door Mirrored Cabinet.jpg",
      price: 395.99,
      alt: "Door Mirrored Cabinet",
      name: "DoorCabinet",
      category: "LivingRoom",
      color: "Brown",
      id: "CliCBrNdo",
    },
    {
      name: "Dining Table",
      price: 564.54,
      imgSrc: "../images/HomeImages/564.webp",
      alt: "DiningTable",
      category: "Dining",
      color: "Gray",
      id: "CdiCgrNdi",
    },
    {
      imgSrc: "../images/shopping/Drawer Accent Chest.jpg",
      price: 419.99,
      alt: "Drawer Accent Chest",
      name: "Drawer Chest",
      category: "LivingRoom",
      color: "Brown",
      id: "CliCBrNdr",
    },
    {
      imgSrc: "../images/shopping/Mid-Century Modern Sofa.jpg",
      price: 799.99,
      alt: "Mid-Century Modern Sofa",
      name: "Modern Sofa",
      category: "LivingRoom",
      color: "Blue",
      id: "CliCblNmo",
    },
    {
      imgSrc: "../images/shopping/Round Abstract Pouf Ottoman.jpg",
      price: 117.99,
      alt: "Round Abstract Pouf Ottoman",
      name: "Round Abstract",
      category: "LivingRoom",
      color: "Orange",
      id: "CliCorNro",
    },
    {
      imgSrc: "../images/shopping/Mcgovern 14'' Steel Bed Frame.jpg",
      price: 229.99,
      alt: "Mcgovern 14'' Steel Bed Frame",
      name: "Steel Bed Frame",
      category: "BedRoom",
      color: "Blue",
      id: "CbeCblNst",
    },
    {
      imgSrc: "../images/shopping/Bassel 2 Piece Sofa Set.jpg",
      price: 799.99,
      alt: "Bassel 2 Piece Sofa Set",
      name: "Bassel Sofa Set",
      category: "LivingRoom",
      color: "Blue",
      id: "CliCblNbas",
    },
    {
      imgSrc: "../images/shopping/Folding Room Divider.jpg",
      price: 136.99,
      alt: "Folding Room Divider",
      name: "Room Divider",
      category: "BedRoom",
      color: "Brown",
      id: "CbeCbrNrod",
    },
    {
      imgSrc: "../images/shopping/Door Accent Cabinet.jpg",
      price: 819.99,
      alt: "Door Accent Cabinet",
      name: "Door Cabinet",
      category: "LivingRoom",
      color: "Brown",
      id: "CliCbrNdoc",
    },
    {
      imgSrc: "../images/shopping/Lynmouth TV Stand for TVs up to.jpg",
      price: 116.5,
      alt: "Lynmouth TV Stand for TVs up to",
      name: "TV Stand",
      category: "LivingRoom",
      color: "Black",
      id: "CliCblaNts",
    },
    {
      imgSrc: "../images/shopping/Chaise Longue With Armrests.jpg",
      price: 864.5,
      alt: "Chaise Longue With Armrests",
      name: "Chaise Longue",
      category: "LivingRoom",
      color: "Red",
      id: "CliCreNchl",
    },
    {
      name: "Shelf",
      price: 352.25,
      imgSrc: "../images/HomeImages/shelf.webp",
      alt: "shelf",
      category: "Office",
      color: "Black",
      id: "CofCblaNshe",
    },
    {
      imgSrc:
        "../images/shopping/Aghadavy Upholstered Low Profile Platform Bed.jpg",
      price: 1030.99,
      alt: "Aghadavy Upholstered Low Profile Platform Bed",
      name: "Platform Bed",
      category: "BedRoom",
      color: "White",
      id: "CbeCwhNplb",
    },
    {
      imgSrc: "../images/shopping/Living Room Set.jpg",
      price: 2700,
      alt: "Living Room Set",
      name: "Living Room Set",
      category: "LivingRoom",
      color: "Gray",
      id: "CliCgrNlir",
    },
    {
      imgSrc: "../images/shopping/Faux Leather Recessed Arm Sofa.jpg",
      price: 802.99,
      alt: "Faux Leather Recessed Arm Sofa",
      name: "Leather Sofa",
      category: "LivingRoom",
      color: "Orange",
      id: "CliCorNles",
      otherImgs: [
        { src: "../images/shopping/Faux Leather Recessed Arm Sofa.jpg", id: 1 },
        { src: "../images/shopping/leather Sofa/1.jpg", id: 2 },
        { src: "../images/shopping/leather Sofa/2.jpg", id: 3 },
        { src: "../images/shopping/leather Sofa/3.jpg", id: 4 },
        { src: "../images/shopping/leather Sofa/4.jpg", id: 5 },
        { src: "../images/shopping/leather Sofa/5.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "cassart",
    },
    {
      imgSrc: "../images/shopping/Middletown Chaise Lounge.jpg",
      price: 759.99,
      alt: "Middletown Chaise Lounge",
      name: "Chaise Lounge",
      category: "LivingRoom",
      color: "Black",
      id: "CliCblaNchl",
    },
    {
      name: "Side Table",
      price: 535,
      imgSrc: "../images/HomeImages/sidetable535.webp",
      alt: "sideTable",
      category: "Office",
      color: "Gray",
      id: "CofCgrNsit",
    },
  ];
}
