export default function getProductImages() {
  return [
    {
      imgSrc: "/images/shopping/sofa/1.jpg",
      price: 1342.44,
      alt: "sofa",
      name: "sofa",
      category: "LivingRoom",
      color: "Gray",
      id: "CaLiCGS",
      otherImgs: [
        { src: "/images/shopping/sofa/1.jpg", id: 1 },
        { src: "/images/shopping/sofa/2.jpg", id: 2 },
        { src: "/images/shopping/sofa/3.jpg", id: 3 },
        { src: "/images/shopping/sofa/4.jpg", id: 4 },
        { src: "/images/shopping/sofa/5.jpg", id: 5 },
      ],
      available: "In Stock",
      brand: "barnet",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/WideLoungeChair.jpg",
      price: 999,
      alt: "Wide Lounge Chair",
      name: "Wide Chair",
      category: "BedRoom",
      color: "Brown",
      id: "CaBeCBWi",
      otherImgs: [
        { src: "/images/shopping/WideLoungeChair.jpg", id: 1 },
        { src: "/images/shopping/Wide Lounge Chair/2.jpg", id: 2 },
        { src: "/images/shopping/Wide Lounge Chair/3.jpg", id: 3 },
        { src: "/images/shopping/Wide Lounge Chair/4.jpg", id: 4 },
        { src: "/images/shopping/Wide Lounge Chair/5.jpg", id: 5 },
      ],
      available: "In Stock",
      brand: "kemcat",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/LeatherSwivelLoungeChair.jpg",
      price: 1599.99,
      alt: "Leather Swivel Lounge Chair",
      name: "Leather Chair",
      category: "BedRoom",
      color: "White",
      id: "CaBeCwNle",
      otherImgs: [
        { src: "/images/shopping/LeatherSwivelLoungeChair.jpg", id: 1 },
        { src: "/images/shopping/leather chair/2.jpg", id: 2 },
        { src: "/images/shopping/leather chair/3.jpg", id: 3 },
        { src: "/images/shopping/leather chair/4.jpg", id: 4 },
        { src: "/images/shopping/leather chair/5.jpg", id: 5 },
        { src: "/images/shopping/leather chair/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "barnet",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Wide Tufted.jpg",
      price: 569.99,
      alt: "Wide Tufted",
      name: "Wide Tufted",
      category: "LivingRoom",
      color: "Gray",
      id: "CliCGrNwi",
      otherImgs: [
        { src: "/images/shopping/Wide Tufted.jpg", id: 1 },
        { src: "/images/shopping/wide tuft/2.jpg", id: 2 },
        { src: "/images/shopping/wide tuft/3.jpg", id: 3 },
        { src: "/images/shopping/wide tuft/4.jpg", id: 4 },
        { src: "/images/shopping/wide tuft/5.jpg", id: 5 },
        { src: "/images/shopping/wide tuft/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "barnet",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Velvet Square Arm Loveseat.jpg",
      price: 689.99,
      alt: "Velvet Square Arm Loveseat",
      name: "Velvet Loveseat",
      category: "LivingRoom",
      color: "White",
      id: "CliCwNve",
      otherImgs: [
        { src: "/images/shopping/Velvet Square Arm Loveseat.jpg", id: 1 },
        { src: "/images/shopping/Velvet Square/2.jpg", id: 2 },
        { src: "/images/shopping/Velvet Square/3.jpg", id: 3 },
        { src: "/images/shopping/Velvet Square/4.jpg", id: 4 },
        { src: "/images/shopping/Velvet Square/5.jpg", id: 5 },
        { src: "/images/shopping/Velvet Square/6.jpg", id: 6 },
      ],
      available: "out of Stock",
      brand: "tolchi",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Door Mirrored Cabinet.jpg",
      price: 395.99,
      alt: "Door Mirrored Cabinet",
      name: "DoorCabinet",
      category: "LivingRoom",
      color: "Brown",
      id: "CliCBrNdo",
      otherImgs: [
        { src: "/images/shopping/Door Mirrored Cabinet.jpg", id: 1 },
        { src: "/images/shopping/Door Mirrored Accent/2.jpg", id: 2 },
        { src: "/images/shopping/Door Mirrored Accent/3.jpg", id: 3 },
        { src: "/images/shopping/Door Mirrored Accent/4.jpg", id: 4 },
        { src: "/images/shopping/Door Mirrored Accent/5.jpg", id: 5 },
        { src: "/images/shopping/Door Mirrored Accent/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "barnet",
      number: 0,
    },
    {
      name: "Dining Table",
      price: 564.54,
      imgSrc: "/images/shopping/dining table/1.jpg",
      alt: "DiningTable",
      category: "Dining",
      color: "Gray",
      id: "CdiCgrNdi",
      otherImgs: [
        { src: "/images/shopping/dining table/1.jpg", id: 1 },
        { src: "/images/shopping/dining table/2.jpg", id: 2 },
      ],
      available: "in Stock",
      brand: "tolchi",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Drawer Accent Chest.jpg",
      price: 419.99,
      alt: "Drawer Accent Chest",
      name: "Drawer Chest",
      category: "LivingRoom",
      color: "Brown",
      id: "CliCBrNdr",
      otherImgs: [
        { src: "/images/shopping/Drawer Accent Chest.jpg", id: 1 },
        { src: "/images/shopping/Drawer Accent/2.jpg", id: 2 },
        { src: "/images/shopping/Drawer Accent/3.jpg", id: 3 },
        { src: "/images/shopping/Drawer Accent/4.jpg", id: 4 },
        { src: "/images/shopping/Drawer Accent/5.jpg", id: 5 },
        { src: "/images/shopping/Drawer Accent/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "comftea",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Mid-Century Modern Sofa.jpg",
      price: 799.99,
      alt: "Mid-Century Modern Sofa",
      name: "Modern Sofa",
      category: "LivingRoom",
      color: "Blue",
      id: "CliCblNmo",
      otherImgs: [
        { src: "/images/shopping/Mid-Century Modern Sofa.jpg", id: 1 },
        { src: "/images/shopping/Mid-Century Modern/2.jpg", id: 2 },
        { src: "/images/shopping/Mid-Century Modern/3.jpg", id: 3 },
        { src: "/images/shopping/Mid-Century Modern/4.jpg", id: 4 },
        { src: "/images/shopping/Mid-Century Modern/5.jpg", id: 5 },
        { src: "/images/shopping/Mid-Century Modern/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "comftea",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Round Abstract Pouf Ottoman.jpg",
      price: 117.99,
      alt: "Round Abstract Pouf Ottoman",
      name: "Round Abstract",
      category: "LivingRoom",
      color: "Orange",
      id: "CliCorNro",
      otherImgs: [
        { src: "/images/shopping/Round Abstract Pouf Ottoman.jpg", id: 1 },
        { src: "/images/shopping/Ottoman/2.jpg", id: 2 },
        { src: "/images/shopping/Ottoman/3.jpg", id: 3 },
        { src: "/images/shopping/Ottoman/4.jpg", id: 4 },
        { src: "/images/shopping/Ottoman/5.jpg", id: 5 },
        { src: "/images/shopping/Ottoman/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "tolchi",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Mcgovern 14'' Steel Bed Frame.jpg",
      price: 229.99,
      alt: "Mcgovern 14'' Steel Bed Frame",
      name: "Steel Bed Frame",
      category: "BedRoom",
      color: "Blue",
      id: "CbeCblNst",
      otherImgs: [
        { src: "/images/shopping/Mcgovern 14'' Steel Bed Frame.jpg", id: 1 },
        { src: "/images/shopping/Steel Bed Frame/2.jpg", id: 2 },
        { src: "/images/shopping/Steel Bed Frame/3.jpg", id: 3 },
        { src: "/images/shopping/Steel Bed Frame/4.jpg", id: 4 },
        { src: "/images/shopping/Steel Bed Frame/5.jpg", id: 5 },
        { src: "/images/shopping/Steel Bed Frame/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "barnet",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Bassel 2 Piece Sofa Set.jpg",
      price: 799.99,
      alt: "Bassel 2 Piece Sofa Set",
      name: "Bassel Sofa Set",
      category: "LivingRoom",
      color: "Blue",
      id: "CliCblNbas",
      otherImgs: [
        { src: "/images/shopping/Bassel 2 Piece Sofa Set.jpg", id: 1 },
        { src: "/images/shopping/Bassel 2 Piece Sofa Set/2.jpg", id: 2 },
        { src: "/images/shopping/Bassel 2 Piece Sofa Set/3.jpg", id: 3 },
      ],
      available: "In Stock",
      brand: "tolchi",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Folding Room Divider.jpg",
      price: 136.99,
      alt: "Folding Room Divider",
      name: "Room Divider",
      category: "BedRoom",
      color: "Brown",
      id: "CbeCbrNrod",
      otherImgs: [
        { src: "/images/shopping/Folding Room Divider.jpg", id: 1 },
        { src: "/images/shopping/Folding Room Divider/2.jpg", id: 2 },
        { src: "/images/shopping/Folding Room Divider/3.jpg", id: 3 },
        { src: "/images/shopping/Folding Room Divider/4.jpg", id: 4 },
        { src: "/images/shopping/Folding Room Divider/5.jpg", id: 5 },
        { src: "/images/shopping/Folding Room Divider/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "vivalet",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Door Accent Cabinet.jpg",
      price: 819.99,
      alt: "Door Accent Cabinet",
      name: "Door Cabinet",
      category: "LivingRoom",
      color: "Brown",
      id: "CliCbrNdoc",
      otherImgs: [
        { src: "/images/shopping/Door Accent Cabinet.jpg", id: 1 },
        { src: "/images/shopping/Door Accent Cabinet/2.jpg", id: 2 },
        { src: "/images/shopping/Door Accent Cabinet/3.jpg", id: 3 },
        { src: "/images/shopping/Door Accent Cabinet/4.jpg", id: 4 },
        { src: "/images/shopping/Door Accent Cabinet/5.jpg", id: 5 },
      ],
      available: "out of Stock",
      brand: "vivalet",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Lynmouth TV Stand for TVs up to.jpg",
      price: 116.5,
      alt: "Lynmouth TV Stand for TVs up to",
      name: "TV Stand",
      category: "LivingRoom",
      color: "Black",
      id: "CliCblaNts",
      otherImgs: [
        {
          src: "/images/shopping/Lynmouth TV Stand for TVs up to.jpg",
          id: 1,
        },
        { src: "/images/shopping/Lynmouth TV Stand/2.jpg", id: 2 },
        { src: "/images/shopping/Lynmouth TV Stand/3.jpg", id: 3 },
        { src: "/images/shopping/Lynmouth TV Stand/4.jpg", id: 4 },
        { src: "/images/shopping/Lynmouth TV Stand/5.jpg", id: 5 },
        { src: "/images/shopping/Lynmouth TV Stand/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "comftea",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Chaise Longue With Armrests.jpg",
      price: 864.5,
      alt: "Chaise Longue With Armrests",
      name: "Chaise Longue",
      category: "LivingRoom",
      color: "Red",
      id: "CliCreNchl",
      otherImgs: [
        { src: "/images/shopping/Chaise Longue With Armrests.jpg", id: 1 },
        { src: "/images/shopping/Chaise Longue With Armrests/2.jpg", id: 2 },
        { src: "/images/shopping/Chaise Longue With Armrests/3.jpg", id: 3 },
        { src: "/images/shopping/Chaise Longue With Armrests/4.jpg", id: 4 },
        { src: "/images/shopping/Chaise Longue With Armrests/5.jpg", id: 5 },
      ],
      available: "out of Stock",
      brand: "vivalet",
      number: 0,
    },
    {
      name: "Shelf",
      price: 352.25,
      imgSrc: "/images/HomeImages/shelf.webp",
      alt: "shelf",
      category: "Office",
      color: "Black",
      id: "CofCblaNshe",
      otherImgs: [
        { src: "/images/HomeImages/shelf.webp", id: 1 },
        { src: "/images/shopping/Shelf/2.webp", id: 2 },
        { src: "/images/shopping/Shelf/3.webp", id: 3 },
        { src: "/images/shopping/Shelf/4.webp", id: 4 },
      ],
      available: "In Stock",
      brand: "barnet",
      number: 0,
    },
    {
      imgSrc:
        "/images/shopping/Aghadavy Upholstered Low Profile Platform Bed.jpg",
      price: 1030.99,
      alt: "Aghadavy Upholstered Low Profile Platform Bed",
      name: "Platform Bed",
      category: "BedRoom",
      color: "White",
      id: "CbeCwhNplb",
      otherImgs: [
        {
          src: "/images/shopping/Aghadavy Upholstered Low Profile Platform Bed.jpg",
          id: 1,
        },
        { src: "/images/shopping/Profile Platform Bed/2.jpg", id: 2 },
        { src: "/images/shopping/Profile Platform Bed/3.jpg", id: 3 },
        { src: "/images/shopping/Profile Platform Bed/4.jpg", id: 4 },
        { src: "/images/shopping/Profile Platform Bed/5.jpg", id: 5 },
        { src: "/images/shopping/Profile Platform Bed/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "kaily",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Living Room Set.jpg",
      price: 2700,
      alt: "Living Room Set",
      name: "Living Room Set",
      category: "LivingRoom",
      color: "Gray",
      id: "CliCgrNlir",
      otherImgs: [
        { src: "/images/shopping/Living Room Set.jpg", id: 1 },
        { src: "/images/shopping/Leather Living Room Set/2.jpg", id: 2 },
        { src: "/images/shopping/Leather Living Room Set/3.jpg", id: 3 },
      ],
      available: "In Stock",
      brand: "kaily",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Faux Leather Recessed Arm Sofa.jpg",
      price: 802.99,
      alt: "Faux Leather Recessed Arm Sofa",
      name: "Leather Sofa",
      category: "LivingRoom",
      color: "Orange",
      id: "CliCorNles",
      otherImgs: [
        { src: "/images/shopping/Faux Leather Recessed Arm Sofa.jpg", id: 1 },
        { src: "/images/shopping/leather Sofa/1.jpg", id: 2 },
        { src: "/images/shopping/leather Sofa/2.jpg", id: 3 },
        { src: "/images/shopping/leather Sofa/3.jpg", id: 4 },
        { src: "/images/shopping/leather Sofa/4.jpg", id: 5 },
        { src: "/images/shopping/leather Sofa/5.jpg", id: 6 },
      ],
      available: "out of Stock",
      brand: "cassart",
      number: 0,
    },
    {
      imgSrc: "/images/shopping/Middletown Chaise Lounge.jpg",
      price: 759.99,
      alt: "Middletown Chaise Lounge",
      name: "Chaise Lounge",
      category: "LivingRoom",
      color: "Black",
      id: "CliCblaNchl",
      otherImgs: [
        { src: "/images/shopping/Middletown Chaise Lounge.jpg", id: 1 },
        { src: "/images/shopping/Middletown Chaise Lounge/2.jpg", id: 2 },
        { src: "/images/shopping/Middletown Chaise Lounge/3.jpg", id: 3 },
        { src: "/images/shopping/Middletown Chaise Lounge/4.jpg", id: 4 },
      ],
      available: "In Stock",
      brand: "kaily",
      number: 0,
    },
    {
      name: "Side Table",
      price: 535,
      imgSrc: "/images/HomeImages/sidetable535.webp",
      alt: "sideTable",
      category: "Office",
      color: "Gray",
      id: "CofCgrNsit",
      otherImgs: [
        { src: "/images/HomeImages/sidetable535.webp", id: 1 },
        { src: "/images/shopping/side table/2.jpg", id: 2 },
        { src: "/images/shopping/side table/3.jpg", id: 3 },
        { src: "/images/shopping/side table/4.jpg", id: 4 },
        { src: "/images/shopping/side table/5.jpg", id: 5 },
        { src: "/images/shopping/side table/6.jpg", id: 6 },
      ],
      available: "out of Stock",
      brand: "kaily",
      number: 0,
    },
  ];
}
