export default function getFeaturedImgs() {
  return [
    {
      imgSrc:
        "/images/shopping/Aghadavy Upholstered Low Profile Platform Bed.jpg",
      price: 1030.99,
      alt: "Aghadavy Upholstered Low Profile Platform Bed",
      name: "Platform Bed",
      category: "BedRoom",
      color: "White",
      id: "CbeCwhNplb",
      otherImgs: [
        {
          src: "/images/shopping/Aghadavy Upholstered Low Profile Platform Bed.jpg",
          id: 1,
        },
        { src: "/images/shopping/Profile Platform Bed/2.jpg", id: 2 },
        { src: "/images/shopping/Profile Platform Bed/3.jpg", id: 3 },
        { src: "/images/shopping/Profile Platform Bed/4.jpg", id: 4 },
        { src: "/images/shopping/Profile Platform Bed/5.jpg", id: 5 },
        { src: "/images/shopping/Profile Platform Bed/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "kaily",
    },
    {
      name: "Side Table",
      price: 535,
      imgSrc: "/images/HomeImages/sidetable535.webp",
      alt: "sideTable",
      category: "Office",
      color: "Gray",
      id: "CofCgrNsit",
      otherImgs: [
        { src: "/images/HomeImages/sidetable535.webp", id: 1 },
        { src: "/images/shopping/side table/2.webp", id: 2 },
        { src: "/images/shopping/side table/3.webp", id: 3 },
        { src: "/images/shopping/side table/4.webp", id: 4 },
        { src: "/images/shopping/side table/5.webp", id: 5 },
        { src: "/images/shopping/side table/6.webp", id: 6 },
      ],
      available: "out of Stock",
      brand: "kaily",
    },
    {
      imgSrc: "/images/shopping/LeatherSwivelLoungeChair.jpg",
      price: 1599.99,
      alt: "Leather Swivel Lounge Chair",
      name: "Leather Chair",
      category: "BedRoom",
      color: "White",
      id: "CaBeCwNle",
      otherImgs: [
        { src: "/images/shopping/LeatherSwivelLoungeChair.jpg", id: 1 },
        { src: "/images/shopping/leather chair/2.jpg", id: 2 },
        { src: "/images/shopping/leather chair/3.jpg", id: 3 },
        { src: "/images/shopping/leather chair/4.jpg", id: 4 },
        { src: "/images/shopping/leather chair/5.jpg", id: 5 },
        { src: "/images/shopping/leather chair/6.jpg", id: 6 },
      ],
      available: "In Stock",
      brand: "barnet",
    },
  ];
}
